### PR TITLE
added deploy script and updated wiki

### PR DESCRIPTION
**Pull request by devnull044**

### CODE REVIEW

**Comment by devnull044** [comment]
#7

**Review by d1vious — CHANGES_REQUESTED** [review]
Do you mind updating the README.md link to point to the Splunk project instead of your fork? Otherwise this looks great! Thank you so much for the contribution!

**Review by devnull044 — COMMENTED** [review]
made changes requested by @d1vious

**Comment by d1vious** [comment]
@devnull044 thank you again for the contribution!

**Pull request merged**
